#!/usr/bin/env bash

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    echo "🔁 Running migrations..."
        php artisan migrate --force

        echo "🌱 Running seeders..."
        php artisan db:seed --force

        echo "🚀 Starting Laravel dev server on port ${PORT:-8000}..."
        exec php artisan serve --host=0.0.0.0 --port=${PORT:-8000}
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    echo "🔁 Running migrations..."
    php artisan migrate --force

    echo "🌱 Running seeders..."
    php artisan db:seed --force

    echo "🚀 Starting Laravel dev server on port ${PORT:-8000}..."
    exec php artisan serve --host=0.0.0.0 --port=${PORT:-8000}
fi
