#!/usr/bin/env bash

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

mkdir -p /.composer
chmod -R ugo+rw /.composer

#echo "🔁 Running migrations..."
#/usr/bin/php8.4 artisan migrate --force
#
#echo "🌱 Running seeders..."
#/usr/bin/php8.4 artisan db:seed --force

#echo "🚀 Starting Laravel dev server on port ${PORT:-8000}..."
#exec /usr/bin/php8.4 artisan serve --host=0.0.0.0 --port=${PORT:-8000}
